   INSERT INTO [dbo].[TRACE_IFS_INTMD_TAB]
    ([DOP_ID]
    ,[CONTRACT]
	,[PART_NO]
	,[DESCRIPTION]
	,[ORDER_NO]
	,[PEGGED_QTY]
	,[NOTE_TEXT]
    ,[LINE_NO]
    ,[CATALOG_DESC]
    ,[WANTED_DELIVERY_DATE]
    ,[LINE_NOTE_TEXT]
    )

  SELECT [DHT].[DOP_ID],[DHT].[CONTRACT],[DHT].[PART_NO],[IPT].[DESCRIPTION] AS PART_DESC,TT2.[ORDER_NO],TT2.[PEGGED_QTY],TT2.[NOTE_TEXT],TT2.[LINE_NO],TT2.[CATALOG_DESC],TT2.[WANTED_DELIVERY_DATE],TT2.[NOTE_TEXT] AS LINE_NOTE_TEXT
	FROM 
	[IFS_LNKD]..[IFSAPP].[DOP_HEAD_TAB]  DHT
	left outer JOIN 
(
	select TT1.*
	from
	(
	
	select DDCOT.*,[CUOT].[NOTE_TEXT],[COLT].[LINE_NO] AS COLT_LINE_NO,[COLT].[CATALOG_DESC],[COLT].[WANTED_DELIVERY_DATE],[COLT].[NOTE_TEXT] AS LINE_NOTE_TEXT
	from
	
	[IFS_LNKD]..[IFSAPP].[DOP_DEMAND_CUST_ORD_TAB]  DDCOT
	
	INNER JOIN 
	[IFS_LNKD]..[IFSAPP].[CUSTOMER_ORDER_TAB]  CUOT
	ON [DDCOT].[ORDER_NO] = [CUOT].[ORDER_NO]
	
	INNER JOIN
	[IFS_LNKD]..[IFSAPP].[CUSTOMER_ORDER_LINE_TAB] COLT
	ON  [COLT].[ORDER_NO] = [DDCOT].[ORDER_NO]
	AND [COLT].[LINE_NO] = [DDCOT].[LINE_NO] 
	AND [COLT].[REL_NO] = [DDCOT].[REL_NO] 
	AND [COLT].[LINE_ITEM_NO] = [DDCOT].[LINE_ITEM_NO]
	
	)
	as
	TT1
	)
	TT2
	
		ON [DHT].[DOP_ID]=TT2.[DOP_ID]
	
	
	INNER JOIN 
	[IFS_LNKD]..[IFSAPP].[INVENTORY_PART_TAB] IPT
	ON [IPT].[PART_NO] = [DHT].[PART_NO]
	
	
WHERE 
--[DHT].[CONTRACT] = 'SRI'
--AND [DHT].[PART_NO]='M222525017502101'

   NOT EXISTS (SELECT * FROM [dbo].[TRACE_IFS_INTMD_TAB] TIIT
              WHERE [DHT].[DOP_ID] = [TIIT].[DOP_ID])
              AND  
              --[DDCOT].[DOP_ID] = 262252 AND
              [DHT].[CONTRACT] = 'SRI' 
              AND [DHT].[ROWSTATE]= 'Released' 
              AND [IPT].[CONTRACT] = 'SRI'
              AND ([DHT].[PART_NO] LIKE '_2%' OR
              [DHT].[PART_NO] LIKE '_7%'
              
              )
              ORDER BY TT2.[WANTED_DELIVERY_DATE] ASC