INSERT INTO [dbo].[TRACE_IFS_INTMD_TAB]
    ([DOP_ID]
    ,[CONTRACT]
	,[PART_NO]
	,[DESCRIPTION]
	,[ORDER_NO]
	,[PEGGED_QTY]
	,[NOTE_TEXT]
    ,[LINE_NO]
    ,[CATALOG_DESC]
    ,[WANTED_DELIVERY_DATE]
    ,[LINE_NOTE_TEXT]
    ,[REL_NO] 
    )
    
    
    SELECT [DHT].[DOP_ID],[DHT].[CONTRACT],[DHT].[PART_NO],[IPT].[DESCRIPTION] AS PART_DESC,[DDCOT].[ORDER_NO],[DDCOT].[PEGGED_QTY],[CUOT].[NOTE_TEXT],[COLT].[LINE_NO],[COLT].[CATALOG_DESC],[COLT].[WANTED_DELIVERY_DATE],[COLT].[NOTE_TEXT] AS LINE_NOTE_TEXT,[DDCOT].[REL_NO] 
	FROM 
	[IFS_LNKD]..[IFSAPP].[DOP_HEAD_TAB]  DHT
	INNER JOIN 
	[IFS_LNKD]..[IFSAPP].[DOP_DEMAND_CUST_ORD_TAB]  DDCOT
	ON [DHT].[DOP_ID]=[DDCOT].[DOP_ID]
	INNER JOIN 
	[IFS_LNKD]..[IFSAPP].[CUSTOMER_ORDER_TAB]  CUOT
	ON 
	[DDCOT].[ORDER_NO]=[CUOT].[ORDER_NO]
	INNER JOIN 
	[IFS_LNKD]..[IFSAPP].[INVENTORY_PART_TAB] IPT
	ON
	[IPT].[PART_NO]=[DHT].[PART_NO]
	INNER JOIN
	[IFS_LNKD]..[IFSAPP].[CUSTOMER_ORDER_LINE_TAB] COLT
	ON
	[DDCOT].[ORDER_NO]=[COLT].[ORDER_NO] AND  [COLT].[LINE_NO]=[DDCOT].[LINE_NO] AND [COLT].[REL_NO]=[DDCOT].[REL_NO] AND [COLT].[LINE_ITEM_NO]=[DDCOT].[LINE_ITEM_NO]
WHERE 
   NOT EXISTS (SELECT * FROM [dbo].[TRACE_IFS_INTMD_TAB] TIIT
              WHERE [DHT].[DOP_ID] = [TIIT].[DOP_ID])
              AND  
              --[DDCOT].[DOP_ID] = 262252 AND
              [DHT].[CONTRACT] = 'SRI' 
              AND [DHT].[ROWSTATE]= 'Released' 
              AND [IPT].[CONTRACT] = 'SRI'
              AND ([DHT].[PART_NO] LIKE '_2%' OR
              [DHT].[PART_NO] LIKE '_7%'
              
              )
              ORDER BY [COLT].[WANTED_DELIVERY_DATE] ASC