select TIIT.DOP_ID,tt.DDCOTDOP_ID
from TRACE_IFS_INTMD_TAB TIIT
right join

(
select tblDerived.* 
from
(
select DHT.DOP_ID as DHTDOP_ID,DHT.CONTRACT as DHTCONTRACT,DHT.PART_NO as DHTPART_NO,DHT.DESCRIPTION as DHTDESCRIPTION,DHT.CREATE_DATE as DHTCREATE_DATE,DHT.LAST_ACTIVITY_DATE as DHTLAST_ACTIVITY_DATE,DDCOT.DOP_ID as DDCOTDOP_ID,DDCOT.ORDER_NO as DDCOTORDER_NO,DDCOT.LINE_NO as DDCOTLINE_NO,DDCOT.REL_NO as DDCOTREL_NO ,COLT.ORDER_NO as COLTORDER_NO,COLT.LINE_NO as COLTLINE_NO,COLT.REL_NO as COLTREL_NO,COLT.CONTRACT as COLTCONTRACT
from [IFS_LNKD]..[IFSAPP].[DOP_HEAD_TAB] DHT
inner join
[IFS_LNKD]..[IFSAPP].[DOP_DEMAND_CUST_ORD_TAB] DDCOT
on
DDCOT.DOP_ID=DHT.DOP_ID
inner join
[IFS_LNKD]..[IFSAPP].[CUSTOMER_ORDER_LINE_TAB] COLT
on
COLT.ORDER_NO=DDCOT.ORDER_NO
and COLT.LINE_NO=DDCOT.Line_No
and COLT.Rel_No=DDCOT.Rel_No
and COLT.Line_Item_No=DDCOT.Line_Item_No
where DHT.CONTRACT = 'SRI' 
              AND DHT.ROWSTATE= 'Released' 
              AND (DHT.PART_NO LIKE '_2%' OR
              DHT.PART_NO LIKE '_7%')
              --ORDER BY DHT.DOP_ID DESC
              
              ) as tblDerived
   ) as tt          
on TIIT.CONTRACT=tt.DHTCONTRACT  
and TIIT.DOP_ID=tt.DDCOTDOP_ID
and TIIT.ORDER_NO=DDCOTORDER_NO
and TIIT.LINE_NO=tt.DDCOTLINE_NO
and TIIT.REL_NO=tt.DDCOTREL_NO  

where tt.DDCOTDOP_ID = '450753' ;

---------------------------------------------------------------------------------------
select tt.DDCOTDOP_ID,TIIT.DOP_ID from

(
select tblDerived.* 
from
(
select DHT.DOP_ID as DHTDOP_ID,DHT.CONTRACT as DHTCONTRACT,DHT.PART_NO as DHTPART_NO,DHT.DESCRIPTION as DHTDESCRIPTION,DHT.CREATE_DATE as DHTCREATE_DATE,DHT.LAST_ACTIVITY_DATE as DHTLAST_ACTIVITY_DATE,DDCOT.DOP_ID as DDCOTDOP_ID,DDCOT.ORDER_NO as DDCOTORDER_NO,DDCOT.LINE_NO as DDCOTLINE_NO,DDCOT.REL_NO as DDCOTREL_NO ,COLT.ORDER_NO as COLTORDER_NO,COLT.LINE_NO as COLTLINE_NO,COLT.REL_NO as COLTREL_NO,COLT.CONTRACT as COLTCONTRACT
from [IFS_LNKD]..[IFSAPP].[DOP_HEAD_TAB] DHT
inner join
[IFS_LNKD]..[IFSAPP].[DOP_DEMAND_CUST_ORD_TAB] DDCOT
on
DDCOT.DOP_ID=DHT.DOP_ID
inner join
[IFS_LNKD]..[IFSAPP].[CUSTOMER_ORDER_LINE_TAB] COLT
on
COLT.ORDER_NO=DDCOT.ORDER_NO
and COLT.LINE_NO=DDCOT.Line_No
and COLT.Rel_No=DDCOT.Rel_No
and COLT.Line_Item_No=DDCOT.Line_Item_No
where DHT.CONTRACT = 'SRI' 
              AND DHT.ROWSTATE= 'Released' 
              AND (DHT.PART_NO LIKE '_2%' OR
              DHT.PART_NO LIKE '_7%')
              --ORDER BY DHT.DOP_ID DESC
              
              ) as tblDerived
  ) as tt
  
  left join
  TRACE_IFS_INTMD_TAB TIIT
  on
  TIIT.CONTRACT=tt.DHTCONTRACT  
and TIIT.DOP_ID=tt.DDCOTDOP_ID
and TIIT.ORDER_NO=DDCOTORDER_NO
and TIIT.LINE_NO=tt.DDCOTLINE_NO
and TIIT.REL_NO=tt.DDCOTREL_NO  

where tt.DDCOTDOP_ID = '451309' ;
 
 -----------------------------------------------------------------------------------------
 
